name: teaching_children

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  audioplayers: ^6.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # package تغيير أيقونة التطبيق
  flutter_launcher_icons: ^0.14.3

# إعدادات الأيقونة
flutter_launcher_icons:
  android: true
  ios: true

  # مكان صورة الأيقونة
  image_path: "assets/images/app_icon.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

    - assets/sounds/أ.mp3
    - assets/sounds/ب.mp3
    - assets/sounds/ت.mp3
    - assets/sounds/ث.mp3
    - assets/sounds/ج.mp3
    - assets/sounds/ح.mp3
    - assets/sounds/خ.mp3
    - assets/sounds/د.mp3
    - assets/sounds/ذ.mp3
    - assets/sounds/ر.mp3
    - assets/sounds/ز.mp3
    - assets/sounds/س.mp3
    - assets/sounds/ش.mp3
    - assets/sounds/ص.mp3
    - assets/sounds/ض.mp3
    - assets/sounds/ط.mp3
    - assets/sounds/ظ.mp3
    - assets/sounds/ع.mp3
    - assets/sounds/غ.mp3
    - assets/sounds/ف.mp3
    - assets/sounds/ق.mp3
    - assets/sounds/ك.mp3
    - assets/sounds/ل.mp3
    - assets/sounds/م.mp3
    - assets/sounds/ن.mp3
    - assets/sounds/ه.mp3
    - assets/sounds/و.mp3
    - assets/sounds/ي.mp3

    - assets/sounds/1.mp3
    - assets/sounds/2.mp3
    - assets/sounds/3.mp3
    - assets/sounds/4.mp3
    - assets/sounds/5.mp3
    - assets/sounds/6.mp3
    - assets/sounds/7.mp3
    - assets/sounds/8.mp3
    - assets/sounds/9.mp3
    - assets/sounds/10.mp3


  fonts:
    - family: ElMessiri

      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf

        - asset: assets/fonts/ElMessiri-Medium.ttf

        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700